### ISSUE TITLE
Карточка товара

### ISSUE THREAD

**Issue by ApexWire** [DarkCs/yupe-theme#1]
http://darkcs.github.io/yupe-theme/product.html
- при выборе третьего изображение тестовый блок смещается вправо 
- при переключении на "Похожие товары" блоки в во вклакде сначало отображаются ужатыми 

![123](https://cloud.githubusercontent.com/assets/2697129/9492739/faf54a4e-4c02-11e5-8505-8760e9a70a37.jpg)

проверял в firefox ubuntu

**Comment by DarkCs** [comment]
1. исправлено, этот баг уже висит у них в трекере больше года https://bugzilla.mozilla.org/show_bug.cgi?id=975632
2. не могу воспроизвести
